# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-21 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(upload_to=b'upload')),
            ],
        ),
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
